
package com.supinfo.suprails.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TripWebService", targetNamespace = "http://webservice.suprails.supinfo.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TripWebService {


    /**
     * 
     * @return
     *     returns java.util.List<com.supinfo.suprails.webservice.Trip>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTrips", targetNamespace = "http://webservice.suprails.supinfo.com/", className = "com.supinfo.suprails.webservice.GetTrips")
    @ResponseWrapper(localName = "getTripsResponse", targetNamespace = "http://webservice.suprails.supinfo.com/", className = "com.supinfo.suprails.webservice.GetTripsResponse")
    @Action(input = "http://webservice.suprails.supinfo.com/TripWebService/getTripsRequest", output = "http://webservice.suprails.supinfo.com/TripWebService/getTripsResponse")
    public List<Trip> getTrips();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "processCustomerOrder", targetNamespace = "http://webservice.suprails.supinfo.com/", className = "com.supinfo.suprails.webservice.ProcessCustomerOrder")
    @ResponseWrapper(localName = "processCustomerOrderResponse", targetNamespace = "http://webservice.suprails.supinfo.com/", className = "com.supinfo.suprails.webservice.ProcessCustomerOrderResponse")
    @Action(input = "http://webservice.suprails.supinfo.com/TripWebService/processCustomerOrderRequest", output = "http://webservice.suprails.supinfo.com/TripWebService/processCustomerOrderResponse")
    public void processCustomerOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        CustomerOrder arg0);

}
